import type { Player } from '@/types/transfer';

/**
 * Known incoming transfer targets and candidates linked to Galatasaray in press coverage.
 * Used for entity resolution and candidate player matching.
 * Squad membership is NEVER hardcoded here; it is resolved dynamically from API-Football.
 */
export const MASTER_PLAYERS_DATA: Player[] = [
  {
    id: 'player-martinelli',
    externalId: 1456,
    name: 'Gabriel Martinelli',
    firstName: 'Gabriel',
    lastName: 'Martinelli',
    position: 'FORWARD',
    currentClub: 'Arsenal',
    nationality: 'Brazil',
    age: 23,
    aliases: ['Martinelli', 'Gabriel Martinelli', 'G. Martinelli'],
  },
  {
    id: 'player-rashford',
    externalId: 899,
    name: 'Marcus Rashford',
    firstName: 'Marcus',
    lastName: 'Rashford',
    position: 'FORWARD',
    currentClub: 'Manchester United',
    nationality: 'England',
    age: 27,
    aliases: ['Rashford', 'Marcus Rashford', 'M. Rashford'],
  },
  {
    id: 'player-leao',
    externalId: 2843,
    name: 'Rafael Leão',
    firstName: 'Rafael',
    lastName: 'Leão',
    position: 'FORWARD',
    currentClub: 'AC Milan',
    nationality: 'Portugal',
    age: 25,
    aliases: ['Leao', 'Rafael Leao', 'Rafael Leão', 'R. Leao'],
  },
  {
    id: 'player-rabiot',
    externalId: 1043,
    name: 'Adrien Rabiot',
    firstName: 'Adrien',
    lastName: 'Rabiot',
    position: 'MIDFIELDER',
    currentClub: 'Marseille',
    nationality: 'France',
    age: 29,
    aliases: ['Rabiot', 'Adrien Rabiot', 'A. Rabiot'],
  },
  {
    id: 'player-fernandes',
    externalId: 1485,
    name: 'Bruno Fernandes',
    firstName: 'Bruno',
    lastName: 'Fernandes',
    position: 'MIDFIELDER',
    currentClub: 'Manchester United',
    nationality: 'Portugal',
    age: 30,
    aliases: ['Bruno Fernandes', 'B. Fernandes'],
  },
  {
    id: 'player-skriniar',
    externalId: 1102,
    name: 'Milan Škriniar',
    firstName: 'Milan',
    lastName: 'Škriniar',
    position: 'DEFENDER',
    currentClub: 'PSG',
    nationality: 'Slovakia',
    age: 29,
    aliases: ['Skriniar', 'Milan Skriniar', 'Milan Škriniar', 'M. Skriniar'],
  },
  {
    id: 'player-arias',
    externalId: 6721,
    name: 'Jhon Arias',
    firstName: 'Jhon',
    lastName: 'Arias',
    position: 'MIDFIELDER',
    currentClub: 'Fluminense',
    nationality: 'Colombia',
    age: 27,
    aliases: ['Arias', 'Jhon Arias', 'J. Arias'],
  },
  {
    id: 'player-bernardo',
    externalId: 629,
    name: 'Bernardo Silva',
    firstName: 'Bernardo',
    lastName: 'Silva',
    position: 'MIDFIELDER',
    currentClub: 'Manchester City',
    nationality: 'Portugal',
    age: 30,
    aliases: ['Bernardo Silva', 'B. Silva', 'Bernardo'],
  },
  {
    id: 'player-nwaneri',
    externalId: 9812,
    name: 'Ethan Nwaneri',
    firstName: 'Ethan',
    lastName: 'Nwaneri',
    position: 'MIDFIELDER',
    currentClub: 'Arsenal',
    nationality: 'England',
    age: 17,
    aliases: ['Nwaneri', 'Ethan Nwaneri', 'E. Nwaneri'],
  },
  {
    id: 'player-dybala',
    externalId: 1205,
    name: 'Paulo Dybala',
    firstName: 'Paulo',
    lastName: 'Dybala',
    position: 'FORWARD',
    currentClub: 'AS Roma',
    nationality: 'Argentina',
    age: 31,
    aliases: ['Dybala', 'Paulo Dybala', 'P. Dybala'],
  },
  {
    id: 'player-hermoso',
    externalId: 2314,
    name: 'Mario Hermoso',
    firstName: 'Mario',
    lastName: 'Hermoso',
    position: 'DEFENDER',
    currentClub: 'AS Roma',
    nationality: 'Spain',
    age: 29,
    aliases: ['Hermoso', 'Mario Hermoso', 'M. Hermoso'],
  },
  {
    id: 'player-ugurcan',
    externalId: 1980,
    name: 'Uğurcan Çakır',
    firstName: 'Uğurcan',
    lastName: 'Çakır',
    position: 'GOALKEEPER',
    currentClub: 'Trabzonspor',
    nationality: 'Turkey',
    age: 28,
    aliases: ['Uğurcan', 'Uğurcan Çakır', 'Ugurcan Cakir'],
  },
];
